const tempScenesSetupData = {
  columns: [
    {
      field: "sceneNo",
      flex: 1,
      headerName: "Scene No.",
    },
    {
      field: "sceneLocation",
      flex: 1,
      headerName: "Scene Location",
      editable: true,
    },
    {
      field: "shootLocation",
      flex: 1,
      headerName: "Shoot Location",
      editable: true,
    },
    {
      field: "shootTime",
      flex: 1,
      headerName: "Shoot Time",
      editable: true,
    },
    {
      field: "screenTime",
      flex: 1,
      headerName: "Screen Time",
      editable: true,
    },
    {
      field: "status",
      flex: 1,
      headerName: "Status",
      editable: true,
    },
    {
      field: "assignedTo",
      flex: 1,
      headerName: "Assigned To",
      editable: true,
    },
    {
      field: "assignedDate",
      flex: 1,
      headerName: "Assigned Date",
      editable: true,
    },
  ],
  rows: [
    {
      id: 1,
      sceneNo: "001",
      sceneLocation: "New York City",
      shootLocation: "Studio A",
      shootTime: "2 hours",
      screenTime: "5 minutes",
      status: "Scheduled",
      assignedTo: "Tony Stark",
      assignedDate: "2023-09-15",
    },
    {
      id: 2,
      sceneNo: "002",
      sceneLocation: "Wakanda",
      shootLocation: "Wakanda Palace",
      shootTime: "3 hours",
      screenTime: "10 minutes",
      status: "In Progress",
      assignedTo: "T'Challa",
      assignedDate: "2023-09-14",
    },
    {
      id: 3,
      sceneNo: "003",
      sceneLocation: "Gotham City",
      shootLocation: "Wayne Manor",
      shootTime: "2.5 hours",
      screenTime: "7 minutes",
      status: "Completed",
      assignedTo: "Bruce Wayne",
      assignedDate: "2023-09-16",
    },
    {
      id: 4,
      sceneNo: "004",
      sceneLocation: "Metropolis",
      shootLocation: "Daily Planet",
      shootTime: "3 hours",
      screenTime: "8 minutes",
      status: "In Progress",
      assignedTo: "Clark Kent",
      assignedDate: "2023-09-18",
    },
    {
      id: 5,
      sceneNo: "005",
      sceneLocation: "Central City",
      shootLocation: "S.T.A.R. Labs",
      shootTime: "2 hours",
      screenTime: "6 minutes",
      status: "Scheduled",
      assignedTo: "Barry Allen",
      assignedDate: "2023-09-17",
    },
    {
      id: 6,
      sceneNo: "006",
      sceneLocation: "Asgard",
      shootLocation: "Bifrost Bridge",
      shootTime: "4 hours",
      screenTime: "15 minutes",
      status: "In Progress",
      assignedTo: "Thor Odinson",
      assignedDate: "2023-09-20",
    },
    {
      id: 7,
      sceneNo: "007",
      sceneLocation: "X-Mansion",
      shootLocation: "Training Room",
      shootTime: "1.5 hours",
      screenTime: "4 minutes",
      status: "Scheduled",
      assignedTo: "Scott Summers",
      assignedDate: "2023-09-19",
    },
    {
      id: 8,
      sceneNo: "008",
      sceneLocation: "S.H.I.E.L.D. Helicarrier",
      shootLocation: "Control Room",
      shootTime: "2 hours",
      screenTime: "7 minutes",
      status: "In Progress",
      assignedTo: "Nick Fury",
      assignedDate: "2023-09-16",
    },
    {
      id: 9,
      sceneNo: "009",
      sceneLocation: "Stark Tower",
      shootLocation: "Conference Room",
      shootTime: "1.5 hours",
      screenTime: "5 minutes",
      status: "Scheduled",
      assignedTo: "Pepper Potts",
      assignedDate: "2023-09-21",
    },
    {
      id: 10,
      sceneNo: "010",
      sceneLocation: "Avengers Compound",
      shootLocation: "Training Grounds",
      shootTime: "2 hours",
      screenTime: "6 minutes",
      status: "In Progress",
      assignedTo: "Steve Rogers",
      assignedDate: "2023-09-14",
    },
    {
      id: 11,
      sceneNo: "011",
      sceneLocation: "Wakanda",
      shootLocation: "Wakandan Vibranium Mine",
      shootTime: "3 hours",
      screenTime: "10 minutes",
      status: "Scheduled",
      assignedTo: "Shuri",
      assignedDate: "2023-09-15",
    },
    {
      id: 12,
      sceneNo: "012",
      sceneLocation: "Gotham City",
      shootLocation: "Batcave",
      shootTime: "2.5 hours",
      screenTime: "8 minutes",
      status: "In Progress",
      assignedTo: "Barbara Gordon",
      assignedDate: "2023-09-18",
    },
    {
      id: 13,
      sceneNo: "013",
      sceneLocation: "Metropolis",
      shootLocation: "LexCorp Tower",
      shootTime: "2 hours",
      screenTime: "7 minutes",
      status: "Scheduled",
      assignedTo: "Lex Luthor",
      assignedDate: "2023-09-19",
    },
    {
      id: 14,
      sceneNo: "014",
      sceneLocation: "Gotham City",
      shootLocation: "GCPD Headquarters",
      shootTime: "1.5 hours",
      screenTime: "5 minutes",
      status: "In Progress",
      assignedTo: "James Gordon",
      assignedDate: "2023-09-16",
    },
    {
      id: 15,
      sceneNo: "015",
      sceneLocation: "X-Mansion",
      shootLocation: "Professor Xavier's Office",
      shootTime: "2 hours",
      screenTime: "6 minutes",
      status: "Scheduled",
      assignedTo: "Charles Xavier",
      assignedDate: "2023-09-21",
    },
    {
      id: 16,
      sceneNo: "016",
      sceneLocation: "S.H.I.E.L.D. Helicarrier",
      shootLocation: "Hangar Bay",
      shootTime: "1.5 hours",
      screenTime: "4 minutes",
      status: "In Progress",
      assignedTo: "Maria Hill",
      assignedDate: "2023-09-17",
    },
    {
      id: 17,
      sceneNo: "017",
      sceneLocation: "Stark Tower",
      shootLocation: "Tony Stark's Lab",
      shootTime: "2 hours",
      screenTime: "7 minutes",
      status: "Scheduled",
      assignedTo: "Bruce Banner",
      assignedDate: "2023-09-16",
    },
    {
      id: 18,
      sceneNo: "018",
      sceneLocation: "Avengers Compound",
      shootLocation: "Common Area",
      shootTime: "2 hours",
      screenTime: "6 minutes",
      status: "In Progress",
      assignedTo: "Natasha Romanoff",
      assignedDate: "2023-09-14",
    },
    {
      id: 19,
      sceneNo: "019",
      sceneLocation: "Wakanda",
      shootLocation: "Wakandan Market",
      shootTime: "3 hours",
      screenTime: "10 minutes",
      status: "Scheduled",
      assignedTo: "Okoye",
      assignedDate: "2023-09-15",
    },
    {
      id: 20,
      sceneNo: "020",
      sceneLocation: "Gotham City",
      shootLocation: "Arkham Asylum",
      shootTime: "2.5 hours",
      screenTime: "8 minutes",
      status: "In Progress",
      assignedTo: "Harley Quinn",
      assignedDate: "2023-09-18",
    },
    {
      id: 21,
      sceneNo: "021",
      sceneLocation: "Central City",
      shootLocation: "CCPD Headquarters",
      shootTime: "2 hours",
      screenTime: "6 minutes",
      status: "In Progress",
      assignedTo: "Iris West-Allen",
      assignedDate: "2023-09-22",
    },
    {
      id: 22,
      sceneNo: "022",
      sceneLocation: "Wakanda",
      shootLocation: "Wakandan Royal Palace",
      shootTime: "3 hours",
      screenTime: "9 minutes",
      status: "Scheduled",
      assignedTo: "Ramonda",
      assignedDate: "2023-09-23",
    },
    {
      id: 23,
      sceneNo: "023",
      sceneLocation: "Metropolis",
      shootLocation: "Metropolis Museum",
      shootTime: "2.5 hours",
      screenTime: "7 minutes",
      status: "In Progress",
      assignedTo: "Lois Lane",
      assignedDate: "2023-09-24",
    },
    {
      id: 24,
      sceneNo: "024",
      sceneLocation: "Gotham City",
      shootLocation: "Joker's Hideout",
      shootTime: "1.5 hours",
      screenTime: "5 minutes",
      status: "Scheduled",
      assignedTo: "Jim Gordon",
      assignedDate: "2023-09-25",
    },
    {
      id: 25,
      sceneNo: "025",
      sceneLocation: "X-Mansion",
      shootLocation: "Cerebro Chamber",
      shootTime: "2 hours",
      screenTime: "6 minutes",
      status: "In Progress",
      assignedTo: "Jean Grey",
      assignedDate: "2023-09-26",
    },
    {
      id: 26,
      sceneNo: "026",
      sceneLocation: "S.H.I.E.L.D. Helicarrier",
      shootLocation: "Medical Bay",
      shootTime: "1.5 hours",
      screenTime: "4 minutes",
      status: "Scheduled",
      assignedTo: "Dr. Helen Cho",
      assignedDate: "2023-09-27",
    },
    {
      id: 27,
      sceneNo: "027",
      sceneLocation: "Stark Tower",
      shootLocation: "Avengers Meeting Room",
      shootTime: "2 hours",
      screenTime: "7 minutes",
      status: "In Progress",
      assignedTo: "Pepper Potts",
      assignedDate: "2023-09-28",
    },
    {
      id: 28,
      sceneNo: "028",
      sceneLocation: "Avengers Compound",
      shootLocation: "Tony Stark's Garage",
      shootTime: "2 hours",
      screenTime: "6 minutes",
      status: "Scheduled",
      assignedTo: "Peter Parker",
      assignedDate: "2023-09-29",
    },
    {
      id: 29,
      sceneNo: "029",
      sceneLocation: "Wakanda",
      shootLocation: "Wakandan Waterfall",
      shootTime: "3 hours",
      screenTime: "10 minutes",
      status: "In Progress",
      assignedTo: "M'Baku",
      assignedDate: "2023-09-30",
    },
    {
      id: 30,
      sceneNo: "030",
      sceneLocation: "Gotham City",
      shootLocation: "Wayne Enterprises",
      shootTime: "2.5 hours",
      screenTime: "8 minutes",
      status: "Scheduled",
      assignedTo: "Lucius Fox",
      assignedDate: "2023-10-01",
    },
    {
      id: 31,
      sceneNo: "031",
      sceneLocation: "Metropolis",
      shootLocation: "LexCorp Research Facility",
      shootTime: "2 hours",
      screenTime: "7 minutes",
      status: "In Progress",
      assignedTo: "Mercy Graves",
      assignedDate: "2023-10-02",
    },
    {
      id: 32,
      sceneNo: "032",
      sceneLocation: "Gotham City",
      shootLocation: "Gotham PD Headquarters",
      shootTime: "1.5 hours",
      screenTime: "5 minutes",
      status: "Scheduled",
      assignedTo: "Renee Montoya",
      assignedDate: "2023-10-03",
    },
    {
      id: 33,
      sceneNo: "033",
      sceneLocation: "X-Mansion",
      shootLocation: "Xavier's School for Gifted Youngsters",
      shootTime: "2 hours",
      screenTime: "6 minutes",
      status: "In Progress",
      assignedTo: "Bobby Drake",
      assignedDate: "2023-10-04",
    },
    {
      id: 34,
      sceneNo: "034",
      sceneLocation: "S.H.I.E.L.D. Helicarrier",
      shootLocation: "Command Bridge",
      shootTime: "1.5 hours",
      screenTime: "4 minutes",
      status: "Scheduled",
      assignedTo: "Maria Hill",
      assignedDate: "2023-10-05",
    },
    {
      id: 35,
      sceneNo: "035",
      sceneLocation: "Stark Tower",
      shootLocation: "Stark Industries Lab",
      shootTime: "2 hours",
      screenTime: "7 minutes",
      status: "In Progress",
      assignedTo: "Hank Pym",
      assignedDate: "2023-10-06",
    },
    {
      id: 36,
      sceneNo: "036",
      sceneLocation: "Avengers Compound",
      shootLocation: "Avengers Gym",
      shootTime: "2 hours",
      screenTime: "6 minutes",
      status: "Scheduled",
      assignedTo: "Carol Danvers",
      assignedDate: "2023-10-07",
    },
    {
      id: 37,
      sceneNo: "037",
      sceneLocation: "Wakanda",
      shootLocation: "Wakandan Council Chamber",
      shootTime: "3 hours",
      screenTime: "10 minutes",
      status: "In Progress",
      assignedTo: "Nakia",
      assignedDate: "2023-10-08",
    },
    {
      id: 38,
      sceneNo: "038",
      sceneLocation: "Gotham City",
      shootLocation: "Arkham Asylum",
      shootTime: "2.5 hours",
      screenTime: "8 minutes",
      status: "Scheduled",
      assignedTo: "Jonathan Crane",
      assignedDate: "2023-10-09",
    },
    {
      id: 39,
      sceneNo: "039",
      sceneLocation: "Metropolis",
      shootLocation: "LexCorp Tower",
      shootTime: "2 hours",
      screenTime: "7 minutes",
      status: "In Progress",
      assignedTo: "Lana Lang",
      assignedDate: "2023-10-10",
    },
    {
      id: 40,
      sceneNo: "040",
      sceneLocation: "Gotham City",
      shootLocation: "Gotham City Hall",
      shootTime: "1.5 hours",
      screenTime: "5 minutes",
      status: "Scheduled",
      assignedTo: "Mayor Hamilton Hill",
      assignedDate: "2023-10-11",
    },
    {
      id: 41,
      sceneNo: "041",
      sceneLocation: "X-Mansion",
      shootLocation: "X-Mansion Library",
      shootTime: "2 hours",
      screenTime: "6 minutes",
      status: "In Progress",
      assignedTo: "Ororo Munroe",
      assignedDate: "2023-10-12",
    },
    {
      id: 42,
      sceneNo: "042",
      sceneLocation: "S.H.I.E.L.D. Helicarrier",
      shootLocation: "S.H.I.E.L.D. Lab",
      shootTime: "1.5 hours",
      screenTime: "4 minutes",
      status: "Scheduled",
      assignedTo: "Fitzsimmons",
      assignedDate: "2023-10-13",
    },
    {
      id: 43,
      sceneNo: "043",
      sceneLocation: "Stark Tower",
      shootLocation: "Avengers Lounge",
      shootTime: "2 hours",
      screenTime: "7 minutes",
      status: "In Progress",
      assignedTo: "Bruce Banner",
      assignedDate: "2023-10-14",
    },
    {
      id: 44,
      sceneNo: "044",
      sceneLocation: "Avengers Compound",
      shootLocation: "Avengers Hangar",
      shootTime: "2 hours",
      screenTime: "6 minutes",
      status: "Scheduled",
      assignedTo: "Natasha Romanoff",
      assignedDate: "2023-10-15",
    },
    {
      id: 45,
      sceneNo: "045",
      sceneLocation: "Wakanda",
      shootLocation: "Wakandan Warrior Falls",
      shootTime: "3 hours",
      screenTime: "10 minutes",
      status: "In Progress",
      assignedTo: "Zuri",
      assignedDate: "2023-10-16",
    },
    {
      id: 46,
      sceneNo: "046",
      sceneLocation: "Gotham City",
      shootLocation: "Gotham Clock Tower",
      shootTime: "2.5 hours",
      screenTime: "8 minutes",
      status: "Scheduled",
      assignedTo: "Barbara Gordon",
      assignedDate: "2023-10-17",
    },
    {
      id: 47,
      sceneNo: "047",
      sceneLocation: "Metropolis",
      shootLocation: "Metropolis Subway",
      shootTime: "2 hours",
      screenTime: "7 minutes",
      status: "In Progress",
      assignedTo: "Jimmy Olsen",
      assignedDate: "2023-10-18",
    },
    {
      id: 48,
      sceneNo: "048",
      sceneLocation: "Gotham City",
      shootLocation: "Iceberg Lounge",
      shootTime: "1.5 hours",
      screenTime: "5 minutes",
      status: "Scheduled",
      assignedTo: "Penguin",
      assignedDate: "2023-10-19",
    },
    {
      id: 49,
      sceneNo: "049",
      sceneLocation: "X-Mansion",
      shootLocation: "Danger Room",
      shootTime: "2 hours",
      screenTime: "6 minutes",
      status: "In Progress",
      assignedTo: "Kurt Wagner",
      assignedDate: "2023-10-20",
    },
    {
      id: 50,
      sceneNo: "050",
      sceneLocation: "S.H.I.E.L.D. Helicarrier",
      shootLocation: "S.H.I.E.L.D. Command Center",
      shootTime: "1.5 hours",
      screenTime: "4 minutes",
      status: "Scheduled",
      assignedTo: "Agent Coulson",
      assignedDate: "2023-10-21",
    },
  ],
};

exports.tempScenesSetupData = tempScenesSetupData;
