const tempArtistsData = [
  {
    id: 1,
    name: "Robert Downey Jr.",
    age: 56,
    gender: "male",
    phone: "123456789",
    eyeColor: "Brown",
    height: "5'8''",
    actingAgeRange: "40-60",
    actualAgeRange: "50-70",
    language: "English",
  },
  {
    id: 2,
    name: "Chris Evans",
    age: 40,
    gender: "male",
    phone: "987654321",
    eyeColor: "Blue",
    height: "6'0''",
    actingAgeRange: "30-50",
    actualAgeRange: "35-55",
    language: "English",
  },
  {
    id: 3,
    name: "Scarlett Johansson",
    age: 36,
    gender: "female",
    phone: "555555555",
    eyeColor: "Green",
    height: "5'4''",
    actingAgeRange: "30-40",
    actualAgeRange: "30-40",
    language: "English",
  },
  {
    id: 4,
    name: "Mark Ruffalo",
    age: 53,
    gender: "male",
    phone: "333333333",
    eyeColor: "Brown",
    height: "5'8''",
    actingAgeRange: "40-60",
    actualAgeRange: "50-70",
    language: "English",
  },
  {
    id: 5,
    name: "Gal Gadot",
    age: 36,
    gender: "female",
    phone: "777777777",
    eyeColor: "Brown",
    height: "5'10''",
    actingAgeRange: "30-40",
    actualAgeRange: "30-40",
    language: "English",
  },
  {
    id: 6,
    name: "Ezra Miller",
    age: 29,
    gender: "male",
    phone: "999999999",
    eyeColor: "Brown",
    height: "6'0''",
    actingAgeRange: "25-35",
    actualAgeRange: "25-35",
    language: "English",
  },
  {
    id: 7,
    name: "Jason Momoa",
    age: 42,
    gender: "male",
    phone: "666666666",
    eyeColor: "Hazel",
    height: "6'4''",
    actingAgeRange: "35-45",
    actualAgeRange: "35-45",
    language: "English",
  },
  {
    id: 8,
    name: "Brie Larson",
    age: 31,
    gender: "female",
    phone: "444444444",
    eyeColor: "Blue",
    height: "5'7''",
    actingAgeRange: "25-35",
    actualAgeRange: "25-35",
    language: "English",
  },
  {
    id: 9,
    name: "Tom Holland",
    age: 25,
    gender: "male",
    phone: "888888888",
    eyeColor: "Brown",
    height: "5'10''",
    actingAgeRange: "20-30",
    actualAgeRange: "20-30",
    language: "English",
  },
  {
    id: 10,
    name: "Chris Hemsworth",
    age: 38,
    gender: "male",
    phone: "222222222",
    eyeColor: "Blue",
    height: "6'3''",
    actingAgeRange: "30-40",
    actualAgeRange: "30-40",
    language: "English",
  },
  {
    id: 11,
    name: "Tom Cruise",
    age: 59,
    gender: "male",
    phone: "111111111",
    eyeColor: "Blue",
    height: "5'7''",
    actingAgeRange: "40-60",
    actualAgeRange: "50-70",
    language: "English",
  },
  {
    id: 12,
    name: "John Krasinski",
    age: 41,
    gender: "male",
    phone: "777777777",
    eyeColor: "Blue",
    height: "6'3''",
    actingAgeRange: "30-45",
    actualAgeRange: "30-45",
    language: "English",
  },
  {
    id: 13,
    name: "Charlize Theron",
    age: 45,
    gender: "female",
    phone: "444444444",
    eyeColor: "Blue",
    height: "5'10''",
    actingAgeRange: "35-50",
    actualAgeRange: "35-50",
    language: "English",
  },
  {
    id: 14,
    name: "Edward Norton",
    age: 51,
    gender: "male",
    phone: "666666666",
    eyeColor: "Green",
    height: "6'0''",
    actingAgeRange: "40-55",
    actualAgeRange: "40-55",
    language: "English",
  },
  {
    id: 15,
    name: "Angelina Jolie",
    age: 46,
    gender: "female",
    phone: "888888888",
    eyeColor: "Brown",
    height: "5'7''",
    actingAgeRange: "35-50",
    actualAgeRange: "35-50",
    language: "English",
  },
  {
    id: 16,
    name: "Grant Gustin",
    age: 31,
    gender: "male",
    phone: "555555555",
    eyeColor: "Green",
    height: "6'0''",
    actingAgeRange: "25-35",
    actualAgeRange: "25-35",
    language: "English",
  },
  {
    id: 17,
    name: "Amber Heard",
    age: 35,
    gender: "female",
    phone: "333333333",
    eyeColor: "Blue",
    height: "5'7''",
    actingAgeRange: "25-35",
    actualAgeRange: "25-35",
    language: "English",
  },
  {
    id: 18,
    name: "Emily Blunt",
    age: 38,
    gender: "female",
    phone: "123456789",
    eyeColor: "Blue",
    height: "5'7''",
    actingAgeRange: "30-40",
    actualAgeRange: "30-40",
    language: "English",
  },
  {
    id: 19,
    name: "Andy Serkis",
    age: 57,
    gender: "male",
    phone: "999999999",
    eyeColor: "Blue",
    height: "5'8''",
    actingAgeRange: "45-60",
    actualAgeRange: "45-60",
    language: "English",
  },
  {
    id: 20,
    name: "Alicia Vikander",
    age: 32,
    gender: "female",
    phone: "111111111",
    eyeColor: "Green",
    height: "5'6''",
    actingAgeRange: "25-35",
    actualAgeRange: "25-35",
    language: "English",
  },
];

module.exports = tempArtistsData;
