const tempSearchLocationData = [
  {
    id: 1,
    title: "Stark Industries",
    subHeader: "New York City",
    status: "Available",
    totalScenes: "5",
    description:
      "Stark Industries, located in the heart of New York City, is a high-tech research and development facility known for its cutting-edge technology and innovative projects.",
    requirements: "Modern, industrial look with advanced machinery",
    selected: false,
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
  },
  {
    id: 2,
    title: "Wakanda",
    subHeader: "African Nation",
    status: "Available",
    totalScenes: "7",
    description:
      "Wakanda is a hidden African nation known for its advanced technology and rich culture. It is home to the powerful Vibranium resource.",
    requirements: "African landscapes, futuristic cityscape",
    selected: false,
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
  },
  {
    id: 3,
    title: "New York City",
    subHeader: "Urban Setting",
    status: "Booked",
    totalScenes: "10",
    description:
      "New York City, the city that never sleeps, is a bustling metropolis known for its iconic skyline, diverse neighborhoods, and vibrant energy.",
    requirements: "Cityscape, various urban locations",
    selected: false,
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
  },
  {
    id: 4,
    title: "Themyscira",
    subHeader: "Paradise Island",
    status: "Available",
    totalScenes: "4",
    description:
      "Themyscira is a mythical island paradise inhabited by Amazonian warriors. It is known for its natural beauty and ancient history.",
    requirements: "Tropical island landscapes, Amazonian architecture",
    selected: false,
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
  },
  {
    id: 5,
    title: "Central City",
    subHeader: "Urban Setting",
    status: "Available",
    totalScenes: "6",
    description:
      "Central City is a modern urban environment known for its fast-paced lifestyle and the presence of The Flash, a superhero with superhuman speed.",
    requirements: "Cityscape, modern architecture",
    selected: false,
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
  },
  {
    id: 6,
    title: "Atlantis",
    subHeader: "Underwater Kingdom",
    status: "Available",
    totalScenes: "3",
    description:
      "Atlantis is a mythical underwater kingdom ruled by Aquaman. It is known for its stunning aquatic landscapes and underwater cities.",
    requirements: "Underwater scenes, marine life, Atlantis architecture",
    selected: false,
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
  },
  {
    id: 7,
    title: "Sanctum Sanctorum",
    subHeader: "Mystical Realm",
    status: "Booked",
    totalScenes: "8",
    description:
      "Sanctum Sanctorum is the mystical residence of Doctor Strange. It is a place of magic and mysticism, hidden within the city.",
    requirements: "Mystical interiors, ancient artifacts, magical elements",
    selected: false,
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
  },
  {
    id: 8,
    title: "X-Mansion",
    subHeader: "School for Mutants",
    status: "Available",
    totalScenes: "9",
    description:
      "X-Mansion is a school for mutants and the headquarters of the X-Men. It is a place of training and refuge for mutant superheroes.",
    requirements:
      "Mansion interiors, high-tech facilities, mutant-friendly environment",
    selected: false,
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
  },
  {
    id: 9,
    title: "Guardians' Spaceship",
    subHeader: "Interstellar Travel",
    status: "Available",
    totalScenes: "2",
    description:
      "The Guardians' spaceship is a state-of-the-art spacecraft used for interstellar adventures. It is equipped with advanced technology and weaponry.",
    requirements: "Spaceship interiors, futuristic design, space scenes",
    selected: false,
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
  },
  {
    id: 10,
    title: "Pym Technologies",
    subHeader: "Scientific Lab",
    status: "Available",
    totalScenes: "4",
    description:
      "Pym Technologies is a scientific research lab known for its groundbreaking work in particle physics and size manipulation technology.",
    requirements: "Advanced lab equipment, scientific setting",
    selected: false,
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
  },
];

module.exports = tempSearchLocationData;
