const tempLocationSetupData = {
  columns: [
    {
      field: "locationName",
      headerName: "Location Name",
      flex: 1,
    },
    {
      field: "noOfScenes",
      headerName: "No of Scenes",
      flex: 1,
      editable: true,
    },
    {
      field: "characterType",
      headerName: "Character Type",
      flex: 1,
      editable: true,
    },
    {
      field: "shootTime",
      headerName: "Shoot Time",
      flex: 1,
      editable: true,
    },
    {
      field: "screenTime",
      headerName: "Screen Time",
      flex: 1,
      editable: true,
    },
    {
      field: "status",
      headerName: "Status",
      flex: 1,
      editable: true,
    },
    {
      field: "assignedTo",
      headerName: "Assigned To",
      flex: 1,
      editable: true,
    },
    {
      field: "assignedDate",
      headerName: "Assigned Date",
      flex: 1,
      editable: true,
    },
  ],
  rows: [
    {
      id: 1,
      locationName: "New York City",
      noOfScenes: 10,
      characterType: "Urban",
      shootTime: "8 hours",
      screenTime: "45 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-15",
    },
    {
      id: 2,
      locationName: "Gotham City",
      noOfScenes: 12,
      characterType: "Urban",
      shootTime: "9 hours",
      screenTime: "60 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-14",
    },
    {
      id: 3,
      locationName: "Asgard",
      noOfScenes: 5,
      characterType: "Mythical",
      shootTime: "6 hours",
      screenTime: "30 minutes",
      status: "Completed",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-16",
    },
    {
      id: 4,
      locationName: "Metropolis",
      noOfScenes: 8,
      characterType: "Urban",
      shootTime: "7 hours",
      screenTime: "50 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-18",
    },
    {
      id: 5,
      locationName: "Wakanda",
      noOfScenes: 6,
      characterType: "Futuristic",
      shootTime: "6 hours",
      screenTime: "40 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-17",
    },
    {
      id: 6,
      locationName: "Sanctum Sanctorum",
      noOfScenes: 4,
      characterType: "Mythical",
      shootTime: "5 hours",
      screenTime: "35 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-20",
    },
    {
      id: 7,
      locationName: "Central City",
      noOfScenes: 7,
      characterType: "Urban",
      shootTime: "6.5 hours",
      screenTime: "45 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-19",
    },
    {
      id: 8,
      locationName: "Atlantis",
      noOfScenes: 3,
      characterType: "Underwater",
      shootTime: "5 hours",
      screenTime: "30 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-16",
    },
    {
      id: 9,
      locationName: "X-Mansion",
      noOfScenes: 9,
      characterType: "Superhero",
      shootTime: "7 hours",
      screenTime: "50 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-21",
    },
    {
      id: 10,
      locationName: "Themyscira",
      noOfScenes: 6,
      characterType: "Mythical",
      shootTime: "6 hours",
      screenTime: "40 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-14",
    },
    {
      id: 11,
      locationName: "Gotham City",
      noOfScenes: 12,
      characterType: "Urban",
      shootTime: "9 hours",
      screenTime: "60 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-14",
    },
    {
      id: 12,
      locationName: "Asgard",
      noOfScenes: 5,
      characterType: "Mythical",
      shootTime: "6 hours",
      screenTime: "30 minutes",
      status: "Completed",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-16",
    },
    {
      id: 13,
      locationName: "Metropolis",
      noOfScenes: 8,
      characterType: "Urban",
      shootTime: "7 hours",
      screenTime: "50 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-18",
    },
    {
      id: 14,
      locationName: "Wakanda",
      noOfScenes: 6,
      characterType: "Futuristic",
      shootTime: "6 hours",
      screenTime: "40 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-17",
    },
    {
      id: 15,
      locationName: "Sanctum Sanctorum",
      noOfScenes: 4,
      characterType: "Mythical",
      shootTime: "5 hours",
      screenTime: "35 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-20",
    },
    {
      id: 16,
      locationName: "Central City",
      noOfScenes: 7,
      characterType: "Urban",
      shootTime: "6.5 hours",
      screenTime: "45 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-19",
    },
    {
      id: 17,
      locationName: "Atlantis",
      noOfScenes: 3,
      characterType: "Underwater",
      shootTime: "5 hours",
      screenTime: "30 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-16",
    },
    {
      id: 18,
      locationName: "X-Mansion",
      noOfScenes: 9,
      characterType: "Superhero",
      shootTime: "7 hours",
      screenTime: "50 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-21",
    },
    {
      id: 19,
      locationName: "Themyscira",
      noOfScenes: 6,
      characterType: "Mythical",
      shootTime: "6 hours",
      screenTime: "40 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-14",
    },
    {
      id: 20,
      locationName: "Sokovia",
      noOfScenes: 5,
      characterType: "Urban",
      shootTime: "5 hours",
      screenTime: "30 minutes",
      status: "Completed",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-15",
    },
    {
      id: 21,
      locationName: "Knowhere",
      noOfScenes: 8,
      characterType: "Extraterrestrial",
      shootTime: "7 hours",
      screenTime: "45 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-18",
    },
    {
      id: 22,
      locationName: "Xandar",
      noOfScenes: 7,
      characterType: "Extraterrestrial",
      shootTime: "6.5 hours",
      screenTime: "50 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-19",
    },
    {
      id: 23,
      locationName: "Asgard",
      noOfScenes: 6,
      characterType: "Mythical",
      shootTime: "6 hours",
      screenTime: "40 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-14",
    },
    {
      id: 24,
      locationName: "Vormir",
      noOfScenes: 3,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "30 minutes",
      status: "Completed",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-16",
    },
    {
      id: 25,
      locationName: "Sakaar",
      noOfScenes: 5,
      characterType: "Extraterrestrial",
      shootTime: "5.5 hours",
      screenTime: "35 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-20",
    },
    {
      id: 26,
      locationName: "Ego",
      noOfScenes: 4,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "40 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-17",
    },
    {
      id: 27,
      locationName: "Xandar Prime",
      noOfScenes: 6,
      characterType: "Extraterrestrial",
      shootTime: "6 hours",
      screenTime: "45 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-19",
    },
    {
      id: 28,
      locationName: "Ego's Planet",
      noOfScenes: 3,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "30 minutes",
      status: "Completed",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-16",
    },
    {
      id: 29,
      locationName: "Vormir",
      noOfScenes: 5,
      characterType: "Extraterrestrial",
      shootTime: "5.5 hours",
      screenTime: "35 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-20",
    },
    {
      id: 30,
      locationName: "Sakaar",
      noOfScenes: 4,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "40 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-17",
    },
    {
      id: 31,
      locationName: "Ego",
      noOfScenes: 6,
      characterType: "Extraterrestrial",
      shootTime: "6 hours",
      screenTime: "45 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-19",
    },
    {
      id: 32,
      locationName: "Xandar Prime",
      noOfScenes: 3,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "30 minutes",
      status: "Completed",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-16",
    },
    {
      id: 33,
      locationName: "Ego's Planet",
      noOfScenes: 5,
      characterType: "Extraterrestrial",
      shootTime: "5.5 hours",
      screenTime: "35 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-20",
    },
    {
      id: 34,
      locationName: "Vormir",
      noOfScenes: 4,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "40 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-17",
    },
    {
      id: 35,
      locationName: "Sakaar",
      noOfScenes: 6,
      characterType: "Extraterrestrial",
      shootTime: "6 hours",
      screenTime: "45 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-19",
    },
    {
      id: 36,
      locationName: "Ego",
      noOfScenes: 3,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "30 minutes",
      status: "Completed",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-16",
    },
    {
      id: 37,
      locationName: "Xandar Prime",
      noOfScenes: 5,
      characterType: "Extraterrestrial",
      shootTime: "5.5 hours",
      screenTime: "35 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-20",
    },
    {
      id: 38,
      locationName: "Ego's Planet",
      noOfScenes: 4,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "40 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-17",
    },
    {
      id: 39,
      locationName: "Vormir",
      noOfScenes: 6,
      characterType: "Extraterrestrial",
      shootTime: "6 hours",
      screenTime: "45 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-19",
    },
    {
      id: 40,
      locationName: "Sakaar",
      noOfScenes: 3,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "30 minutes",
      status: "Completed",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-16",
    },
    {
      id: 41,
      locationName: "Ego",
      noOfScenes: 5,
      characterType: "Extraterrestrial",
      shootTime: "5.5 hours",
      screenTime: "35 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-20",
    },
    {
      id: 42,
      locationName: "Xandar Prime",
      noOfScenes: 4,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "40 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-17",
    },
    {
      id: 43,
      locationName: "Ego's Planet",
      noOfScenes: 6,
      characterType: "Extraterrestrial",
      shootTime: "6 hours",
      screenTime: "45 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-19",
    },
    {
      id: 44,
      locationName: "Vormir",
      noOfScenes: 3,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "30 minutes",
      status: "Completed",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-16",
    },
    {
      id: 45,
      locationName: "Sakaar",
      noOfScenes: 5,
      characterType: "Extraterrestrial",
      shootTime: "5.5 hours",
      screenTime: "35 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-20",
    },
    {
      id: 46,
      locationName: "Ego",
      noOfScenes: 4,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "40 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-17",
    },
    {
      id: 47,
      locationName: "Xandar Prime",
      noOfScenes: 6,
      characterType: "Extraterrestrial",
      shootTime: "6 hours",
      screenTime: "45 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-19",
    },
    {
      id: 48,
      locationName: "Ego's Planet",
      noOfScenes: 3,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "30 minutes",
      status: "Completed",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-16",
    },
    {
      id: 49,
      locationName: "Vormir",
      noOfScenes: 5,
      characterType: "Extraterrestrial",
      shootTime: "5.5 hours",
      screenTime: "35 minutes",
      status: "In Progress",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-20",
    },
    {
      id: 50,
      locationName: "Sakaar",
      noOfScenes: 4,
      characterType: "Extraterrestrial",
      shootTime: "5 hours",
      screenTime: "40 minutes",
      status: "Scheduled",
      assignedTo: "Location Manager",
      assignedDate: "2023-09-17",
    },
  ],
};

exports.tempLocationSetupData = tempLocationSetupData;
