const tempSceneLocationsData = [
  {
    id: 1,
    name: "Times Square",
    city: "New York",
    country: "USA",
    image: "times_square.jpg",
  },
  {
    id: 2,
    name: "Eiffel Tower",
    city: "Paris",
    country: "France",
    image: "eiffel_tower.jpg",
  },
  {
    id: 3,
    name: "Hollywood Sign",
    city: "Los Angeles",
    country: "USA",
    image: "hollywood_sign.jpg",
  },
  {
    id: 4,
    name: "Grand Canyon",
    city: "Arizona",
    country: "USA",
    image: "grand_canyon.jpg",
  },
  {
    id: 5,
    name: "Machu Picchu",
    city: "Aguas Calientes",
    country: "Peru",
    image: "machu_picchu.jpg",
  },
  {
    id: 6,
    name: "Taj Mahal",
    city: "Agra",
    country: "India",
    image: "taj_mahal.jpg",
  },
  {
    id: 7,
    name: "Great Wall of China",
    city: "Beijing",
    country: "China",
    image: "great_wall.jpg",
  },
  {
    id: 8,
    name: "Santorini",
    city: "Thira",
    country: "Greece",
    image: "santorini.jpg",
  },
  {
    id: 9,
    name: "Sydney Opera House",
    city: "Sydney",
    country: "Australia",
    image: "sydney_opera_house.jpg",
  },
  {
    id: 10,
    name: "Dubai Desert",
    city: "Dubai",
    country: "UAE",
    image: "dubai_desert.jpg",
  },
  {
    id: 11,
    name: "Mount Fuji",
    city: "Tokyo",
    country: "Japan",
    image: "mount_fuji.jpg",
  },
  {
    id: 12,
    name: "The Colosseum",
    city: "Rome",
    country: "Italy",
    image: "colosseum.jpg",
  },
  {
    id: 13,
    name: "Mesa Arch",
    city: "Utah",
    country: "USA",
    image: "mesa_arch.jpg",
  },
  {
    id: 14,
    name: "Santorini",
    city: "Thira",
    country: "Greece",
    image: "santorini.jpg",
  },
  {
    id: 15,
    name: "Victoria Falls",
    city: "Livingstone",
    country: "Zambia",
    image: "victoria_falls.jpg",
  },
  {
    id: 16,
    name: "The Pyramids of Giza",
    city: "Cairo",
    country: "Egypt",
    image: "pyramids_of_giza.jpg",
  },
  {
    id: 17,
    name: "The Amazon Rainforest",
    city: "Iquitos",
    country: "Peru",
    image: "amazon_rainforest.jpg",
  },
  {
    id: 18,
    name: "Niagara Falls",
    city: "Niagara Falls",
    country: "Canada",
    image: "niagara_falls.jpg",
  },
  {
    id: 19,
    name: "Venice Canals",
    city: "Venice",
    country: "Italy",
    image: "venice_canals.jpg",
  },
  {
    id: 20,
    name: "The Louvre",
    city: "Paris",
    country: "France",
    image: "the_louvre.jpg",
  },
];

exports.tempSceneLocationsData = tempSceneLocationsData;
