export const loremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed nisi lacus sed viverra tellus in hac habitasse. Ac odio tempor orci dapibus ultrices in iaculis. Tellus at urna condimentum mattis pellentesque. Proin sed libero enim sed faucibus turpis in eu. Vestibulum lectus mauris ultrices eros. Ultricies tristique nulla aliquet enim. Varius duis at consectetur lorem donec massa sapien faucibus. Pellentesque pulvinar pellentesque habitant morbi. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque.

Neque aliquam vestibulum morbi blandit. In ante metus dictum at tempor commodo. Dictum at tempor commodo ullamcorper a lacus vestibulum sed. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Ut diam quam nulla porttitor massa. Pretium viverra suspendisse potenti nullam ac tortor vitae. Viverra suspendisse potenti nullam ac tortor vitae. In aliquam sem fringilla ut morbi. Id nibh tortor id aliquet lectus proin nibh nisl. Amet dictum sit amet justo donec. Neque volutpat ac tincidunt vitae semper quis lectus nulla.

Penatibus et magnis dis parturient montes nascetur ridiculus. Mauris pharetra et ultrices neque ornare aenean euismod elementum nisi. Laoreet id donec ultrices tincidunt arcu non sodales. Vulputate dignissim suspendisse in est ante in nibh. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Nulla pharetra diam sit amet. Curabitur gravida arcu ac tortor dignissim convallis aenean et. Tristique nulla aliquet enim tortor at auctor urna nunc id. Amet aliquam id diam maecenas ultricies mi eget mauris. Blandit aliquam etiam erat velit. Placerat duis ultricies lacus sed turpis tincidunt id aliquet risus. Risus nec feugiat in fermentum posuere urna. Fringilla ut morbi tincidunt augue interdum velit euismod. Quam viverra orci sagittis eu. Ut sem viverra aliquet eget sit. Vulputate dignissim suspendisse in est ante in nibh mauris cursus.

Dui sapien eget mi proin sed. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Pharetra magna ac placerat vestibulum lectus. Ac tortor vitae purus faucibus. Volutpat ac tincidunt vitae semper quis lectus nulla at. Senectus et netus et malesuada. Dignissim convallis aenean et tortor at. Blandit massa enim nec dui nunc mattis enim. In arcu cursus euismod quis viverra. Integer vitae justo eget magna fermentum iaculis eu non. Ut aliquam purus sit amet luctus venenatis lectus magna. In iaculis nunc sed augue lacus viverra.

Mattis nunc sed blandit libero volutpat sed cras ornare. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Mattis molestie a iaculis at erat. Faucibus pulvinar elementum integer enim. Tellus at urna condimentum mattis pellentesque id nibh tortor. Purus gravida quis blandit turpis cursus. Mauris pharetra et ultrices neque ornare aenean euismod elementum nisi. Blandit turpis cursus in hac habitasse platea. Lorem sed risus ultricies tristique nulla. Tincidunt augue interdum velit euismod in pellentesque massa placerat. Aliquam id diam maecenas ultricies mi. Tortor dignissim convallis aenean et tortor at risus viverra. Blandit aliquam etiam erat velit scelerisque in dictum. Mollis aliquam ut porttitor leo a. Mattis enim ut tellus elementum sagittis vitae et leo. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Maecenas volutpat blandit aliquam etiam erat velit. Neque egestas congue quisque egestas diam. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Commodo elit at imperdiet dui accumsan sit amet.`;

export const directorListItems = [
  {
    text: "Director Home",
    icon: "GroupIcon",
    route: "/director",
  },
  {
    text: "Verify Crew",
    icon: "GroupIcon",
    route: "/director/verifyCrew",
  },
  {
    text: "Scene Input",
    icon: "PersonIcon",
    route: "/director/sceneInput",
  },
  {
    text: "Shoot Duration",
    icon: "PersonIcon",
    route: "/director/shootDuration",
  },
  {
    text: "Character Input",
    icon: "BarChartIcon",
    route: "/director/characterInput",
  },
  {
    text: "Location Input",
    icon: "BarChartIcon",
    route: "/director/locationInput",
  },
  {
    text: "Schedule Output",
    icon: "BarChartIcon",
    route: "/director/scheduleOutput",
  },
];

export const tempCrewData = {
  columns: [
    {
      field: "id",
      headerName: "ID",
      width: 100,
    },
    {
      field: "name",
      headerName: "Name",
      width: 200,
      editable: true,
    },
    {
      field: "department",
      headerName: "Department",
      width: 200,
      editable: true,
    },
    {
      field: "designation",
      headerName: "Designation",
      width: 200,
      editable: true,
    },
    {
      field: "subDepartment",
      headerName: "Sub Department",
      width: 200,
      editable: true,
    },
  ],
  rows: [
    {
      id: 1,
      name: "Tony Stark",
      department: "Stark Industries",
      designation: "CEO",
      subDepartment: "Technology",
    },
    {
      id: 2,
      name: "Steve Rogers",
      department: "Avengers",
      designation: "Super Soldier",
      subDepartment: "Superheroes",
    },
    {
      id: 3,
      name: "Natasha Romanoff",
      department: "S.H.I.E.L.D.",
      designation: "Black Widow",
      subDepartment: "Espionage",
    },
    {
      id: 4,
      name: "Peter Parker",
      department: "Daily Bugle",
      designation: "Photographer",
      subDepartment: "Journalism",
    },
    {
      id: 5,
      name: "Wanda Maximoff",
      department: "Wakanda",
      designation: "Scarlet Witch",
      subDepartment: "Mystic Arts",
    },
    {
      id: 6,
      name: "Bruce Banner",
      department: "Gamma Labs",
      designation: "Scientist",
      subDepartment: "Research",
    },
    {
      id: 7,
      name: "Matt Murdock",
      department: "Nelson & Murdock",
      designation: "Lawyer",
      subDepartment: "Legal Services",
    },
    {
      id: 8,
      name: "Wade Wilson",
      department: "Mercenaries Inc.",
      designation: "Deadpool",
      subDepartment: "Mercenary",
    },
    {
      id: 9,
      name: "Ororo Munroe",
      department: "X-Mansion",
      designation: "Storm",
      subDepartment: "Weather Control",
    },
    {
      id: 10,
      name: "Scott Summers",
      department: "X-Mansion",
      designation: "Cyclops",
      subDepartment: "Team Leader",
    },
    {
      id: 11,
      name: "Jean Grey",
      department: "X-Mansion",
      designation: "Phoenix",
      subDepartment: "Telepathy",
    },
    {
      id: 12,
      name: "Loki Laufeyson",
      department: "Asgard",
      designation: "Trickster",
      subDepartment: "Mischief",
    },
    {
      id: 13,
      name: "Peter Quill",
      department: "Guardians of the Galaxy",
      designation: "Star-Lord",
      subDepartment: "Space Exploration",
    },
    {
      id: 14,
      name: "Gamora",
      department: "Guardians of the Galaxy",
      designation: "Assassin",
      subDepartment: "Combat",
    },
    {
      id: 15,
      name: "T'Challa",
      department: "Wakanda",
      designation: "Black Panther",
      subDepartment: "Wakandan Affairs",
    },
    {
      id: 16,
      name: "Carol Danvers",
      department: "Kree Starforce",
      designation: "Captain Marvel",
      subDepartment: "Cosmic Protection",
    },
    {
      id: 17,
      name: "Doctor Strange",
      department: "Sanctum Sanctorum",
      designation: "Sorcerer Supreme",
      subDepartment: "Mystic Arts",
    },
    {
      id: 18,
      name: "Nick Fury",
      department: "S.H.I.E.L.D.",
      designation: "Director",
      subDepartment: "Strategic Operations",
    },
    {
      id: 19,
      name: "Clint Barton",
      department: "Avengers",
      designation: "Hawkeye",
      subDepartment: "Archery",
    },
    {
      id: 20,
      name: "Erik Lehnsherr",
      department: "X-Mansion",
      designation: "Magneto",
      subDepartment: "Magnetic Control",
    },
    {
      id: 21,
      name: "Nebula",
      department: "Guardians of the Galaxy",
      designation: "Cyborg",
      subDepartment: "Technology",
    },
    {
      id: 22,
      name: "Hank Pym",
      department: "Pym Technologies",
      designation: "Ant-Man",
      subDepartment: "Particle Physics",
    },
    {
      id: 23,
      name: "Diana Prince",
      department: "Themyscira",
      designation: "Wonder Woman",
      subDepartment: "Amazonian Warriors",
    },
    {
      id: 24,
      name: "Barry Allen",
      department: "Central City Police",
      designation: "The Flash",
      subDepartment: "Speed Force",
    },
    {
      id: 25,
      name: "Arthur Curry",
      department: "Atlantis",
      designation: "Aquaman",
      subDepartment: "Oceanic Guardians",
    },
    {
      id: 26,
      name: "Victor Stone",
      department: "S.T.A.R. Labs",
      designation: "Cyborg",
      subDepartment: "Cybernetics",
    },
    {
      id: 27,
      name: "Logan",
      department: "X-Mansion",
      designation: "Wolverine",
      subDepartment: "Mutant Operations",
    },
    {
      id: 28,
      name: "Groot",
      department: "Guardians of the Galaxy",
      designation: "I am Groot",
      subDepartment: "Flora Colossus",
    },
    {
      id: 29,
      name: "Rocket",
      department: "Guardians of the Galaxy",
      designation: "Rocket Raccoon",
      subDepartment: "Engineering",
    },
    {
      id: 30,
      name: "Pietro Maximoff",
      department: "Avengers",
      designation: "Quicksilver",
      subDepartment: "Super Speed",
    },
    {
      id: 31,
      name: "Stephen Strange",
      department: "Sanctum Sanctorum",
      designation: "Doctor Strange",
      subDepartment: "Mystic Arts",
    },
    {
      id: 32,
      name: "J. Jonah Jameson",
      department: "Daily Bugle",
      designation: "Editor-in-Chief",
      subDepartment: "Journalism",
    },
    {
      id: 33,
      name: "Rhodey Rhodes",
      department: "U.S. Air Force",
      designation: "War Machine",
      subDepartment: "Military Technology",
    },
    {
      id: 34,
      name: "Pepper Potts",
      department: "Stark Industries",
      designation: "COO",
      subDepartment: "Corporate Affairs",
    },
    {
      id: 35,
      name: "Gwen Stacy",
      department: "Daily Bugle",
      designation: "Reporter",
      subDepartment: "Journalism",
    },
    {
      id: 36,
      name: "Frank Castle",
      department: "NYPD",
      designation: "The Punisher",
      subDepartment: "Vigilante Justice",
    },
    {
      id: 37,
      name: "Jean Grey",
      department: "X-Mansion",
      designation: "Jean Grey",
      subDepartment: "Telepathy",
    },
    {
      id: 38,
      name: "Loki Laufeyson",
      department: "Asgard",
      designation: "Loki",
      subDepartment: "Mischief",
    },
    {
      id: 39,
      name: "Erik Killmonger",
      department: "Wakanda",
      designation: "Killmonger",
      subDepartment: "Warrior",
    },
    {
      id: 40,
      name: "Sam Wilson",
      department: "Avengers",
      designation: "Falcon",
      subDepartment: "Aerial Recon",
    },
    {
      id: 41,
      name: "Jessica Jones",
      department: "Alias Investigations",
      designation: "Private Investigator",
      subDepartment: "Detective Work",
    },
    {
      id: 42,
      name: "Luke Cage",
      department: "Heroes for Hire",
      designation: "Power Man",
      subDepartment: "Strength",
    },
    {
      id: 43,
      name: "Peggy Carter",
      department: "S.H.I.E.L.D.",
      designation: "Agent Carter",
      subDepartment: "Espionage",
    },
    {
      id: 44,
      name: "Hank McCoy",
      department: "X-Mansion",
      designation: "Beast",
      subDepartment: "Scientific Research",
    },
    {
      id: 45,
      name: "T'Chaka",
      department: "Wakanda",
      designation: "Black Panther",
      subDepartment: "Former King",
    },
    {
      id: 46,
      name: "J. Jonah Jameson",
      department: "Daily Bugle",
      designation: "Editor-in-Chief",
      subDepartment: "Journalism",
    },
    {
      id: 47,
      name: "Carol Danvers",
      department: "Kree Starforce",
      designation: "Captain Marvel",
      subDepartment: "Cosmic Protection",
    },
    {
      id: 48,
      name: "Thor Odinson",
      department: "Asgard",
      designation: "Thor",
      subDepartment: "God of Thunder",
    },
    {
      id: 49,
      name: "Scott Lang",
      department: "Pym Technologies",
      designation: "Ant-Man",
      subDepartment: "Size Manipulation",
    },
    {
      id: 50,
      name: "Diana Prince",
      department: "Themyscira",
      designation: "Wonder Woman",
      subDepartment: "Amazonian Warriors",
    },
  ]
};
